name: Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./github/actions/setup

      - uses: codecov/codecov-action@v3

      - name: Install
        run: pnpm i

      - name: coverage
        run: pnpm run test:test
